name = "plaintxt Theme"
license = "MIT"
licenselink = "https://github.com/defphil/plaintxt-hugo-theme/blob/master/LICENSE.md"
description = "Brutalist, minimalistic, pure text theme like it's 1999."
homepage = "https://github.com/defphil/simple-hugo-theme"
tags = ["blog", "minimal", "clean", "light"]
features = ["small page size", "fast"]
min_version = "0.40"

[author]
  name = "Filip Miletic"
  homepage = "https://github.com/defphil"
